modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MPL2.0"
issueTrackerURL="https://github.com/Xwaffle1/CobblemonExtras/issues"

[[mods]] #mandatory
modId="cobblemonextras" #mandatory
version="${version}" #mandatory
displayName="Cobblemon Extras" #mandatory
displayURL="https://chasem.dev"
#logoFile="examplemod.png" #optional
credits="Thanks to the Cobblemon Community."
authors="Cobblemon Extras"
description='''
 Adds special commands to CobblemonExtras
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.cobblemonextras]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"

[[dependencies.cobblemonextras]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory

[[dependencies.cobblemonextras]]
modId="architectury"
mandatory=true
versionRange="[6.5.69,)"